version: "3"
services:
  database:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=lemoncat
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    network_mode: "host"
  web:
    image: 127.0.0.1:3841
    depends_on:
      - database
    container_name: app
    volumes:
      - /home/ltdat6499/Desktop/lemoncat:/app
    build:
      context: .
    ports:
      - "3841:3841"
    network_mode: "host"
volumes:
  database_data: 